name: detectree
channels:
  - conda-forge
dependencies:
  - click
  - contextily
  - descartes
  - detectree=0.6.0
  - geopandas>=1
  - matplotlib
  - numpy>=2
  - osmnx>=1
  - python=3.12
  - python-slugify
  - pip
  - pip:
    - -e .
    - laspy[lazrs]>=2
  - rasterio
  - shapely
